server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: user
  devtools:
    livereload.enabled: true
    restart.enabled: true
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(1rilHJ3Hk+PdZtcNXvssvMKgO65y4KVELyRLqXM38m+acsJOZDGh+0zNKmFZCnquE4DTdv/xJQfJspwsJDwMzB05ZlzfADT+zE7ZKkQMp4cPMvZLT6buDg==)
    hikari:
      username: ENC(8/pfxOuBbUw1iExsqdmj4w==)
      password: ENC(1qoMWBqW70Kc8EOL/hCz8w==)
      connectionTimeout: 10000
      maximum-pool-size: 15
      max-lifetime: 600000
      readOnly: false
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

jasypt:
  encryptor:
    # JasyptConfig에 정의한 빈 이름
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )